
set(HEPMC2_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../external/HepMC" CACHE PATH "Location of HepMC 2 installation")
set(HEPMC3_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../external/HepMC3" CACHE PATH "Location of HepMC 3 installation")

if(DEFINED ENV{PYTHIAVER})
    set(PYTHIA8_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../external/pythia$ENV{PYTHIAVER}" CACHE PATH "Location of Pythia8 installation")
else()
    set(PYTHIA8_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../external/pythia8230" CACHE PATH "Location of Pythia8 installation")
endif()
set(Photos++_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../external/PHOTOS" CACHE PATH "Location of Photos++ installation")
set(Tauola++_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../external/TAUOLA" CACHE PATH "Location of Tauola++ installation")
set(PHOTOSPP_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../external/PHOTOS" CACHE PATH "Location of Photos++ installation/alternative spelling")
set(TAUOLAPP_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../external/TAUOLA" CACHE PATH "Location of Tauola++ installation/alternative spelling")

#Here we are looking for HepMC interfaces. Note that the OPTIONAL_COMPONENTS includes the libraries that appear only in the new TAUOLA/PHOTOS
if (EVTGEN_HEPMC3)
find_package(HepMC3 REQUIRED)
if(${EVTGEN_PYTHIA})
    find_package(Pythia8 REQUIRED)
endif()
if(${EVTGEN_PHOTOS})
    find_package(Photos++ REQUIRED COMPONENTS pp ppHepMC3)
endif()
if(${EVTGEN_TAUOLA})
    find_package(Tauola++ REQUIRED COMPONENTS Fortran CxxInterface HepMC3)
endif()
else()
find_package(HepMC2 REQUIRED)
if(${EVTGEN_PYTHIA})
    find_package(Pythia8 REQUIRED)
endif()
if(${EVTGEN_PHOTOS})
    find_package(Photos++ REQUIRED OPTIONAL_COMPONENTS pp ppHepMC CxxInterface Fortran)
endif()
if(${EVTGEN_TAUOLA})
    find_package(Tauola++ REQUIRED  COMPONENTS Fortran CxxInterface OPTIONAL_COMPONENTS HepMC)
endif()
endif()
